export type BlogPost = {
  slug: string
  title: string
  excerpt: string
  category: string
  date: string
  readTime: string
  image: string
  author: string
  authorTitle: string
  authorImage: string
  content: string[]
}

export const blogPosts: BlogPost[] = [
  {
    slug: "kitchen-renovation-mistakes",
    title: "10 Kitchen Renovation Mistakes to Avoid Before Your Toaster Develops Trust Issues",
    excerpt: "A practical guide to avoiding the classic kitchen disasters that turn a tidy remodel into a flour-covered hostage situation.",
    category: "Kitchen",
    date: "April 2, 2025",
    readTime: "8 min read",
    image: "/images/kitchen-mistakes.png",
    author: "Sarah Johnson",
    authorTitle: "Interior Designer",
    authorImage: "/placeholder.svg?height=100&width=100",
    content: [
      "Kitchen renovations are popular because everybody wants a beautiful kitchen. They are terrifying because the kitchen is also where the coffee lives, and removing the coffee zone turns ordinary adults into Victorian ghosts by day three.",
      "Mistake one is setting a fantasy budget. If your spreadsheet assumes nothing hidden is broken behind the wall, your spreadsheet is not a plan. It is historical fiction.",
      "The kitchen work triangle still matters. A layout that looks incredible on Pinterest but requires twelve steps to get from sink to stove will eventually be judged by someone carrying boiling pasta.",
      "Choose appliances early. Cabinets, clearances, and services all depend on them. Buying the fridge last is how people discover their dream appliance has the dimensions of a midsize hatchback.",
      "Lighting deserves more attention than it usually gets. A kitchen should support chopping vegetables, finding cumin, and quietly judging your life choices at 11 p.m. without relying on one exhausted ceiling light.",
    ],
  },
  {
    slug: "bathroom-budget-remodel",
    title: "Bathroom Remodeling on a Budget, or How to Spend Less in the Splash Zone",
    excerpt: "Smart ways to improve a bathroom without turning a humble refresh into a tiny tiled money furnace.",
    category: "Bathroom",
    date: "March 28, 2025",
    readTime: "6 min read",
    image: "/images/bathroom-budget.png",
    author: "Marcus Lee",
    authorTitle: "Renovation Planner",
    authorImage: "/placeholder.svg?height=100&width=100",
    content: [
      "A tight bathroom budget does not mean the room has to feel sad. It does mean every decision should work hard, because bathrooms are tiny spaces with the financial appetite of a much larger building.",
      "Keeping the plumbing layout in place is still the biggest saver. Moving a toilet sounds simple until you realize the floor, the waste line, and your bank account all have strong feelings about it.",
      "Spend where people actually notice. Better tapware, lighting, mirrors, and a decent vanity can do more for the room than blowing the budget on imported tile named after an Italian cloud formation.",
      "If you want the room to feel calm and intentional, reduce tile complexity. Every extra niche, feature strip, and fancy cut is another opportunity for labor costs to put on a cape and fly away.",
    ],
  },
  {
    slug: "eco-friendly-renovations",
    title: "Eco-Friendly Renovations for People Who Recycle but Also Like Hot Showers",
    excerpt: "How to make smarter, lower-waste renovation choices without acting like sustainability requires misery or beige everything.",
    category: "Sustainability",
    date: "March 25, 2025",
    readTime: "7 min read",
    image: "/images/eco-friendly.png",
    author: "Priya Nair",
    authorTitle: "Sustainable Design Consultant",
    authorImage: "/placeholder.svg?height=100&width=100",
    content: [
      "Sustainable renovation starts with keeping good things out of the skip. The greenest cabinet is often the one you did not unnecessarily replace because it lacked 'main character energy.'",
      "The biggest wins usually come from insulation, sealing drafts, improving glazing, and upgrading heating or cooling. These are less glamorous than artisanal tiles, but they keep paying rent long after the tiles stop being exciting.",
      "Durability matters as much as recycled content. A product that lasts twenty years is often a better environmental choice than a virtuous-sounding material that gives up at the first sign of sunlight and inconvenience.",
      "Ask about sourcing and lead times early. Sustainable options are excellent until they vanish from stock and your builder starts suggesting whatever is available in alarming quantities.",
    ],
  },
  {
    slug: "home-addition-guide",
    title: "How to Plan a Home Addition Without Accidentally Inventing a Very Expensive Shed",
    excerpt: "A grounded guide to planning extra space without losing control of approvals, scope, or your remaining sanity.",
    category: "Planning",
    date: "March 20, 2025",
    readTime: "9 min read",
    image: "/placeholder.svg?height=600&width=1200",
    author: "Daniel Brooks",
    authorTitle: "Project Manager",
    authorImage: "/placeholder.svg?height=100&width=100",
    content: [
      "Home additions go wrong when people fall in love with a floor plan before checking whether the site, budget, or local rules are prepared to support that love.",
      "Confirm setbacks, easements, and planning constraints first. It is far cheaper to redraw a concept than to discover the dream room is legally allowed only if it becomes six percent smaller and emotionally disappointing.",
      "Treat the connection points to the existing house as high-risk zones. New work meeting old structure is where surprises gather, compare notes, and invoice you together.",
      "Plan how people will actually live during the build. Dust, access, noise, temporary kitchens, and one bathroom for four humans can all become stronger project memories than the final room itself.",
    ],
  },
  {
    slug: "flooring-selection-guide",
    title: "Choosing the Right Flooring for Each Room and Each Slightly Damp Disaster",
    excerpt: "A practical guide to floors that survive real life, including muddy shoes, dripping laundry, and the occasional dropped spaghetti.",
    category: "Flooring",
    date: "March 15, 2025",
    readTime: "5 min read",
    image: "/placeholder.svg?height=600&width=1200",
    author: "Elena Cruz",
    authorTitle: "Materials Specialist",
    authorImage: "/placeholder.svg?height=100&width=100",
    content: [
      "Flooring choices should be based on moisture, impact, cleaning requirements, and your household's proven commitment to walking indoors like a herd of decorative buffalo.",
      "Bathrooms and laundries need water tolerance first. Kitchens need something that handles spills, foot traffic, and the emotional violence of dropping a full jar of passata.",
      "Bedrooms can prioritize warmth and acoustics because nobody dreams of waking up onto a surface that feels like an airport terminal.",
      "Always compare the warranty to the real substrate and install method. Many flooring failures are not product failures. They are communication failures wearing a timber-look costume.",
    ],
  },
  {
    slug: "diy-vs-professional",
    title: "DIY vs. Professional: A Helpful Guide to Knowing When Confidence Is Not a Qualification",
    excerpt: "How to decide which jobs you can handle yourself and which ones deserve a licensed adult with insurance.",
    category: "DIY",
    date: "March 10, 2025",
    readTime: "6 min read",
    image: "/placeholder.svg?height=600&width=1200",
    author: "Tom Wheeler",
    authorTitle: "Licensed Builder",
    authorImage: "/placeholder.svg?height=100&width=100",
    content: [
      "DIY works best when the task is low-risk, repetitive, and inspectable. Painting, prep, demolition planning, and simple install work are often reasonable. Rewiring a switchboard because you watched three confident videos at midnight is less reasonable.",
      "Bring in licensed trades for waterproofing, structure, gas, and regulated electrical work. These are not the categories where you want to discover your hidden talent for consequences.",
      "The smartest approach is often hybrid. Owners can handle planning, procurement, protection, and cosmetic finishing while professionals cover the technical systems and sign-off points.",
      "If your mistake would require another trade to undo it before they can start, hire earlier. Cheap professional advice at the right time can save thousands and dramatically reduce the phrase 'while we're here.'",
    ],
  },
  {
    slug: "paint-colors-guide",
    title: "How to Choose Paint Colors Without Eventually Choosing 'Some Kind of Beige'",
    excerpt: "A survival guide for anyone who has ever stood in a hardware store for 47 minutes holding sample chips and feeling feelings.",
    category: "Design",
    date: "March 5, 2025",
    readTime: "7 min read",
    image: "/placeholder.svg?height=600&width=1200",
    author: "Rachel Torres",
    authorTitle: "Color Consultant",
    authorImage: "/placeholder.svg?height=100&width=100",
    content: [
      "Paint is the cheapest way to transform a room and the fastest way to regret everything. The difference between success and disaster is usually testing samples properly, which means painting actual patches on actual walls and not just imagining what 'Sage Serenity' looks like.",
      "Natural light changes everything. The colour you fell in love with at noon will not be the same colour at 4 PM when the room starts looking like a cave with opinions.",
      "Test in multiple spots on the wall. Paint reacts differently to corners, ceilings, and whatever is happening near the light switch. One sample patch is not a sample. It is a trap.",
      "Commit to a colour for at least a week before panicking. Paint looks different wet, different when it first dries, and different after your furniture moves back in. Give it time to stop being dramatic.",
      "If you are choosing between three colours that all look the same to you, they are not the same. Look again. One has more grey, one has more warmth, and one is definitely 'Sea Salt' which is a lie because the sea does not smell like that.",
    ],
  },
  {
    slug: "lighting-fundamentals",
    title: "Lighting 101: Why Your Kitchen Has One Light and Your Dreams Have None",
    excerpt: "Understanding layers, lumens, and why changing a lightbulb is not a personality but it should be.",
    category: "Design",
    date: "February 28, 2025",
    readTime: "8 min read",
    image: "/placeholder.svg?height=600&width=1200",
    author: "James Chen",
    authorTitle: "Electrical Designer",
    authorImage: "/placeholder.svg?height=100&width=100",
    content: [
      "Good lighting is invisible. You notice it only when it is missing or when you walk into someone else's house and everything looks annoyingly good.",
      "Three layers work better than one. Task lighting for work surfaces, ambient lighting for general visibility, and accent lighting for the things you want to look intentional.",
      "Undercabinet lighting is not optional anymore. It was optional when people cooked less and ordered takeout more. We have evolved.",
      "Dimmers are cheap and solving problems they did not know existed. Getting a dimmer installed when you do not have one is easier than convincing yourself you do not need one.",
      "Color temperature matters more than people think. 2700K is warm and cozy. 4000K is clinical and wakes you up. 5000K is for garages and people who are processing invoices.",
    ],
  },
  {
    slug: "cabinet-selection-guide",
    title: "Cabinet Selection: Why IKEA Is Sometimes Right and Custom Is Sometimes a Trap",
    excerpt: "A completely practical guide to cabinets that does not judge you for whatever you choose, but does judge the decisions that lead to regret.",
    category: "Kitchen",
    date: "February 22, 2025",
    readTime: "9 min read",
    image: "/placeholder.svg?height=600&width=1200",
    author: "Sarah Johnson",
    authorTitle: "Interior Designer",
    authorImage: "/placeholder.svg?height=100&width=100",
    content: [
      "Cabinets are the most expensive decision in most kitchens. The gap between a good cabinet and a foolish one is usually about four thousand dollars and one argument about shaker doors.",
      "IKEA cabinets are underrated and also correctly rated. The hardware is annoying. The price is real. The finished result is frequently indistinguishable from cabinets that cost three times more.",
      "Custom cabinets make sense when your kitchen is not a standard shape. If you have odd angles, unusual depths, or a specific vision that cannot be achieved with modular systems, custom is worth the premium.",
      "Soft-close hinges should not be a luxury feature in 2025. They just should not. If a cabinet door is slamming in your house, that is a problem and also a sound that nobody should have to hear anymore.",
      "Plywood boxes outperform particleboard in humid environments. If your cabinets are near a dishwasher or a sink, pay the extra money for plywood. Your cabinets will survive the marriage.",
    ],
  },
  {
    slug: "window-selection-guide",
    title: "Windows: The Part of Your House That Costs Too Much and Does Too Much",
    excerpt: "Understanding U-values, SHGC, and why the window salesperson knows more than you do but maybe not in a helpful way.",
    category: "Planning",
    date: "February 18, 2025",
    readTime: "7 min read",
    image: "/placeholder.svg?height=600&width=1200",
    author: "Michael Park",
    authorTitle: "Window Specialist",
    authorImage: "/placeholder.svg?height=100&width=100",
    content: [
      "Windows are sold on performance metrics that require a engineering degree to decode. U-value measures heat transfer. SHGC measures solar heat gain. Together they tell you whether your windows will perform or just performatively look expensive.",
      "Double glazing is standard. Triple glazing is for people in cold climates or people who have strong feelings about their heating bills. Double is usually enough unless you live somewhere with actual winters.",
      "Frame material matters. Vinyl is affordable and low maintenance. Aluminum is strong and narrow-sightline. Fiberglass is expensive and performs well. Wood is beautiful and also a commitment.",
      "Installation is where windows fail. A perfect window installed poorly will leak air, accumulate condensation, and generally make you wonder why you spent so much on a window that does not behave like a window.",
      "Size and placement matter as much as the window itself. Bigger is not always better. Sometimes more natural light means more heat gain, more glare, and more neighbors asking why you are starring in your own reality show.",
    ],
  },
  {
    slug: "hvac-renovation-guide",
    title: "HVAC: The System You Ignore Until It Makes a Sound That Sounds Like a Sound Nothing Should Make",
    excerpt: "A practical guide to heating and cooling that will not make you an expert but will make you a less confused person.",
    category: "Systems",
    date: "February 12, 2025",
    readTime: "10 min read",
    image: "/placeholder.svg?height=600&width=1200",
    author: "Roberto Silva",
    authorTitle: "HVAC Technician",
    authorImage: "/placeholder.svg?height=100&width=100",
    content: [
      "HVAC is complicated in proportion to how much you rely on it. If you live somewhere temperate, you might not need to think about it much. If you live somewhere with actual seasons, you need to think about it seriously.",
      "Sizing matters more than brand. An oversized unit short-cycles, wastes energy, and fails faster. An undersized unit runs constantly and still cannot keep up. Manual J calculations exist for a reason. Use them.",
      "Ductwork is underrated. New equipment installed in aging ductwork will underperform. The duct system delivers the comfort. The equipment makes the comfort. Both need to work.",
      "Zoning is worth considering when different rooms have different uses or different temperature preferences. A zone system lets you treat different areas differently instead of arguing about the thermostat constantly.",
      "Maintenance is boring and necessary. Changing filters regularly is the one thing homeowners can do that makes the biggest difference. Everything else requires a professional who will arrive in a van and diagnose things you cannot.",
    ],
  },
  {
    slug: "outdoor-living-spaces",
    title: "Outdoor Living: How to Turn Your Backyard Into a Place Adults Actually Want to Be",
    excerpt: "Because the deck is for holding plants and the BBQ is for the one day a year it rains.",
    category: "Outdoor",
    date: "February 5, 2025",
    readTime: "6 min read",
    image: "/placeholder.svg?height=600&width=1200",
    author: "Lisa Chen",
    authorTitle: "Landscape Designer",
    authorImage: "/placeholder.svg?height=100&width=100",
    content: [
      "Outdoor living is not just about furniture. It is about creating zones, shade, and purpose so that the outdoor space does something for the household instead of just existing and judging everyone from the other side of the sliding door.",
      "Define the zones before buying furniture. Lounge area, cooking area, dining area. Each zone needs a reason to exist and enough space to actually function. Cramming a six-seater dining set onto a patio meant for four is how relationships get tested.",
      "Shade is non-negotiable in warm climates. Umbrellas are portable. Pergolas are permanent. Both beat the alternative, which is going inside because direct sun has turned your outdoor time into a competitive sweating event.",
      "Materials matter outdoors more than indoors. Wind, rain, UV, and temperature changes all attack outdoor materials in ways indoor materials never experience. Choose accordingly. Your local hardware store has information about regional suitability that Google does not.",
      "Lighting extends usability into evening. String lights are festive. Path lights are practical. Both beat stumbling to the BBQ in the dark at 9 PM wondering why you cannot find the tongs.",
    ],
  },
  {
    slug: "small-bathroom-solutions",
    title: "Small Bathroom Solutions: Making Tiny Spaces Feel Less Like You Are Renovating a Bus Bathroom",
    excerpt: "Spatial illusions, fixture choices, and the subtle art of not hating your only bathroom.",
    category: "Bathroom",
    date: "January 28, 2025",
    readTime: "7 min read",
    image: "/placeholder.svg?height=600&width=1200",
    author: "Nina Patel",
    authorTitle: "Bathroom Specialist",
    authorImage: "/placeholder.svg?height=100&width=100",
    content: [
      "Small bathrooms are not small problems. They require the same plumbing, the same ventilation, and the same desire to not feel cramped, all in less space. The challenge is real and the solutions are specific.",
      "Wall-mounted fixtures create visual space. A floating vanity or a wall-hung toilet does not actually add square footage, but they make the floor more visible, which makes the room feel larger.",
      "Glass shower screens beat shower curtains every time in small bathrooms. A curtain makes a small shower feel even smaller. A clear glass screen maintains visual continuity and does not collapse dramatically every time someone moves.",
      "Large mirrors work harder than any other trick. One large mirror reflects light and makes the room feel doubled. Two smaller mirrors fight each other and accomplish nothing except needing to be cleaned twice.",
      "Pedestal sinks leave floor space visible. Vanities provide storage. The choice depends on whether your household can survive without hidden storage or whether everyone will suffer. Be honest about this.",
    ],
  },
  {
    slug: "storage-solutions-guide",
    title: "Storage Solutions That Do Not Require a Pinterest Board or a Shed",
    excerpt: "Because every house has enough stuff and not enough places for the stuff. This is a universal law, like gravity but worse.",
    category: "Organization",
    date: "January 20, 2025",
    readTime: "6 min read",
    image: "/placeholder.svg?height=600&width=1200",
    author: "Amanda Foster",
    authorTitle: "Organization Consultant",
    authorImage: "/placeholder.svg?height=100&width=100",
    content: [
      "Storage is never enough. This is a fact of life that renovation can address but never fully solve. The goal is to build enough storage that the stuff has a home and the home does not feel like a storage unit with a sofa.",
      "Vertical space is underutilized. Tall shelving units, overhead storage in garages, and wall-mounted organization systems all take advantage of height that most rooms waste.",
      "Multi-functional furniture earns its place in smaller homes. A bed with drawers, a dining table with leaves, and an ottoman with storage all serve two purposes without doubling the furniture footprint.",
      "Built-in storage is more expensive but more effective. Custom cabinetry, window seats with storage, and built-in bookshelves use space more efficiently than freestanding furniture and generally look less like you are living in a showroom.",
      "Declutter before renovating. Adding storage without removing clutter is like trying to fill a bathtub while the drain is open. Figure out what is actually staying in the house before building places for things to live.",
    ],
  },
  {
    slug: "energy-efficiency-retrofit",
    title: "Energy Efficiency Retrofits: Lower Bills, Warmer House, Fewer Excuses",
    excerpt: "A practical guide to making an older home perform better without turning it into a museum of good intentions.",
    category: "Sustainability",
    date: "January 15, 2025",
    readTime: "8 min read",
    image: "/placeholder.svg?height=600&width=1200",
    author: "David Wright",
    authorTitle: "Energy Auditor",
    authorImage: "/placeholder.svg?height=100&width=100",
    content: [
      "Energy efficiency retrofits are the highest-return renovation investment most people ignore. The payback periods are clear, the comfort improvements are real, and the environmental benefit is genuine. Yet most people prioritize a new kitchen over sealing their drafty old windows.",
      "Air sealing is usually the first move. Finding where air leaks in a house takes an energy audit or a cold day and a candle. The common leak points are around windows, doors, ceiling penetrations, and wherever something was installed by someone who was in a hurry.",
      "Insulation is the second move and the one people think about first. Attic insulation is usually the biggest win because heat rises and escapes. Wall insulation is more complicated but often achievable without removing drywall.",
      "Windows are the controversial one. Replacing windows costs significant money and provides real but sometimes slower payback than other measures. If the windows are genuinely old and inefficient, replacement makes sense. If they are decent, sealing and window treatments might be enough.",
      "Appliances and systems matter. An old hot water system, an inefficient furnace, or a refrigerator that sounds like a dying aircraft all consume more energy than they need to. Upgrading them has clear returns and immediate comfort benefits.",
    ],
  },
  {
    slug: "laundry-room-renovation",
    title: "Laundry Room Renovation: Making the Room You Cannot Escape Slightly Less Torturous",
    excerpt: "Because doing laundry is already unpleasant enough without the room actively contributing to your misery.",
    category: "Laundry",
    date: "January 8, 2025",
    readTime: "6 min read",
    image: "/placeholder.svg?height=600&width=1200",
    author: "Chris Martinez",
    authorTitle: "Laundry Room Evangelist",
    authorImage: "/placeholder.svg?height=100&width=100",
    content: [
      "The laundry room is the room nobody renovates until it becomes a room that needs renovating. Then it becomes the most important room in the house because nobody can agree on what constitutes a 'delicates' cycle.",
      "Location matters. If your laundry room is on the second floor near the bedrooms, you are winning the location lottery. If it is in the basement next to the boiler, you are living in a house that was designed by someone who hated laundry.",
      "Counter space is non-negotiable. Folding clothes on a dryer is for people who have given up on elegance. A simple counter next to the washer gives you a folding station and makes the room actually usable.",
      "Storage for detergents, supplies, and the random item that somehow always migrates to the laundry room needs to be intentional. Open shelving works. Cabinets keep things less visible. Both beat the system of storing laundry supplies wherever they land.",
      "Lighting in laundry rooms is usually an afterthought. A laundry room should be well-lit because sorting colors requires seeing colors. One overhead light is not enough. Task lighting over the folding area makes the room actually functional.",
    ],
  },
  {
    slug: "garage-renovation-guide",
    title: "Garage Conversions: The Space You Have Been Wasting on Things You Said You Would Sort",
    excerpt: "A garage full of boxes labeled 'miscellaneous' is not storage. It is a shrine to good intentions that stopped at the door.",
    category: "Garage",
    date: "January 3, 2025",
    readTime: "7 min read",
    image: "/placeholder.svg?height=600&width=1200",
    author: "Tom Wheeler",
    authorTitle: "Licensed Builder",
    authorImage: "/placeholder.svg?height=100&width=100",
    content: [
      "Garages are the most underutilized spaces in most houses. They hold the car (sometimes), the stuff (always), and the promise of a future workshop (rarely realized). Converting a garage to living space is not a small decision, but it is sometimes the right one.",
      "Conversion requires treating the space like a real room. That means insulation, climate control, proper flooring, and lighting that does not make the space feel like a place where cars go to be sad.",
      "Parking vs. living is the core tradeoff. If you have off-street parking elsewhere, converting the garage is simpler. If the garage is your only covered parking, removing it has consequences for vehicle condition and property value.",
      "Permits and regulations vary. A garage conversion might require planning consent, building regulations approval, and compliance with minimum room sizes, ventilation requirements, and means of escape provisions. Check before committing.",
      "The transition from garage to room usually involves addressing the floor level difference, the garage door situation, and the fact that garages are not typically designed to be watertight from the inside out. These are solvable problems. They just cost money.",
    ],
  },
  {
    slug: "home-office-renovation",
    title: "The Home Office Renovation: Because Your Kitchen Table Has Heard Enough About Spreadsheets",
    excerpt: "A guide to building a workspace that supports productivity without convincing your household you have built a second office and will now be unavailable for all chores.",
    category: "Office",
    date: "December 28, 2024",
    readTime: "7 min read",
    image: "/placeholder.svg?height=600&width=1200",
    author: "Rachel Torres",
    authorTitle: "Color Consultant",
    authorImage: "/placeholder.svg?height=100&width=100",
    content: [
      "The pandemic proved that home offices are necessary and that a corner of a bedroom is not a home office. The market has not fully absorbed this lesson, but renovated homes with dedicated workspaces are increasingly valuable.",
      "Location and quiet matter more than size. A small room with a door that closes is infinitely better than a large open plan space where every household noise becomes your background track.",
      "Desk placement affects everything. Natural light is good for mood but bad for screen glare. Facing the wall is good for focus but bad for feeling connected. The ideal desk position usually involves some compromise.",
      "Storage in a home office is different from storage in other rooms. Paper, supplies, equipment, and the category of 'miscellaneous items that have migrated from other rooms' all need homes. Built-in shelving works better than freestanding furniture for most people.",
      "Technology infrastructure is often overlooked. The ideal home office has ethernet access, sufficient power outlets, cable management, and enough USB ports that charging devices does not require a PhD in physics.",
    ],
  },
  {
    slug: "hvac-maintenance-guide",
    title: "HVAC Maintenance: The System You Ignore Until It Makes a Sound That Sounds Like a Sound Nothing Should Make",
    excerpt: "A practical guide to keeping your heating and cooling system running efficiently before it becomes a very expensive emotional event.",
    category: "Systems",
    date: "December 20, 2024",
    readTime: "6 min read",
    image: "/placeholder.svg?height=600&width=1200",
    author: "Roberto Silva",
    authorTitle: "HVAC Technician",
    authorImage: "/placeholder.svg?height=100&width=100",
    content: [
      "HVAC systems have two seasons: heating season and cooling season. Each season ends with a breakdown that could have been prevented with two hours of maintenance in the shoulder season. The shoulder season is now. Please do not wait until January to think about this.",
      "Filters are the single most important maintenance item. Change them every 1-3 months depending on usage and environment. A dirty filter makes your system work harder, costs more to run, and produces air quality that is technically breathable in the same way that cave water is technically hydration.",
      "Thermostat batteries should be checked twice a year. This sounds obvious. This still catches people every winter when the thermostat starts displaying nothing and the house is already cold.",
      "Outdoor units need clearing. Leaves, debris, and sometimes small animals accumulate around outdoor units. Give the unit clear space. Trim vegetation. Occasionally check for animal nests because animals do not pay rent and they will move in.",
      "Professional maintenance makes sense once a year. A technician catches things that homeowners miss, lubricates moving parts, checks refrigerant levels, and generally prevents the emergency service call that costs three times as much as the maintenance visit would have.",
    ],
  },
  {
    slug: "plumbing-basics",
    title: "Plumbing Basics: What Every Homeowner Should Know Before Calling a Plumber",
    excerpt: "Save money and embarrassment by knowing the difference between a pipe and a problem.",
    category: "Plumbing",
    date: "December 15, 2024",
    readTime: "7 min read",
    image: "/placeholder.svg?height=600&width=1200",
    author: "Mike Torres",
    authorTitle: "Master Plumber",
    authorImage: "/placeholder.svg?height=100&width=100",
    content: [
      "Every homeowner should know where their main water shutoff is. This knowledge becomes important during bursts, emergencies, and when you want to avoid a small leak becoming a large bill. Write the location on a sticky note. Put it somewhere visible. Test that it actually shuts off because some valves have opinions about being exercised.",
      "The difference between a plumbing emergency and a plumbing inconvenience is often time. A running toilet is inconvenient. A burst pipe is an emergency. Both get worse if ignored. The toilet will increase your water bill. The burst pipe will increase your insurance claim.",
      "Drain cleaners are not your friend. They work sometimes and destroy pipes the other times. The better approach: a plunger, then a snake, then acceptance that you need to call someone with proper tools.",
      "Know what you can flush. The rule is simple: human waste and toilet paper only. Everything else eventually becomes a problem that requires a plumber and a的心情 that requires a vacation.",
      "Slow drains are usually hair and soap buildup. Remove the drain cover, clean it, use a snake if needed. If multiple drains are slow, the problem is deeper in the system and likely requires professional attention.",
    ],
  },
  {
    slug: "electrical-safety",
    title: "Electrical Safety: When to Call an Electrician and When to Feel Proud of Yourself",
    excerpt: "A guide to knowing the difference between a safe DIY electrical job and a future story about how the house almost burned down.",
    category: "Electrical",
    date: "December 10, 2024",
    readTime: "6 min read",
    image: "/placeholder.svg?height=600&width=1200",
    author: "David Chen",
    authorTitle: "Licensed Electrician",
    authorImage: "/placeholder.svg?height=100&width=100",
    content: [
      "Electrical work has one rule: when in doubt, stop. Electricity is not the place for confident guesses. The consequences of being wrong are not repair costs. They are structural damage and insurance claims that get denied.",
      "Changing outlets and switches is generally within DIY reach if you turn off the breaker, test with a voltage tester, and follow basic safety practices. Replacing a light fixture is usually fine. Running new circuits is not.",
      "Warning signs that indicate electrical problems: flickering lights, warm outlets, burning smells from outlets, circuit breakers that trip repeatedly. These are not quirks. They are requests for professional attention.",
      "Tamper-resistant outlets are now code in most jurisdictions for new construction. If your home has old outlets without the little plastic barriers, consider upgrading. Especially if you have children or plan to have children visit.",
      "Outdoor electrical is different. Outlets, lighting, and equipment designed for outdoor use have weather resistance ratings that indoor equipment does not. Using indoor equipment outdoors is how electrical problems become outdoor electrical problems.",
    ],
  },
  {
    slug: "attic-renovation",
    title: "Attic Renovations: Adding Space Without Adding a New Foundation",
    excerpt: "How to evaluate whether your attic can become the extra room you have been pretending it could be.",
    category: "Room Addition",
    date: "December 5, 2024",
    readTime: "8 min read",
    image: "/placeholder.svg?height=600&width=1200",
    author: "Sarah Johnson",
    authorTitle: "Interior Designer",
    authorImage: "/placeholder.svg?height=100&width=100",
    content: [
      "Attic conversions are appealing because they use existing structure. No foundation needed. No adding to the building footprint. Just making the forgotten space above your ceiling into something useful.",
      "The critical questions: ceiling height, floor structure, and access. Building codes usually require at least half the floor area to have ceiling heights of at least 7 feet. If your attic was designed as storage, the floor structure may not support living loads. And stairs are not optional if you expect regular use.",
      "Headroom is usually the limiting factor. What looks like plenty of space when you are standing at the peak becomes less space as you move toward the exterior walls. Measure carefully. The room you imagined is not always the room you can actually build.",
      "Insulation and ventilation need attention in attics. insulation goes on the floor. Ventilation goes in the rafters. These are different jobs and confusing them creates problems that involve mold and structural damage.",
      "Access stairs take up floor space and ceiling space. A proper staircase requires headroom at the bottom. This is a surprisingly large commitment in a home where space is already at a premium.",
    ],
  },
  {
    slug: "basement-finishing",
    title: "Basement Finishing: The Room That Costs More Than You Think and Delivers Less Than You Imagined",
    excerpt: "A realistic guide to finishing a basement that helps you budget for the reality instead of the dream.",
    category: "Room Addition",
    date: "November 28, 2024",
    readTime: "7 min read",
    image: "/placeholder.svg?height=600&width=1200",
    author: "Tom Wheeler",
    authorTitle: "Licensed Builder",
    authorImage: "/placeholder.svg?height=100&width=100",
    content: [
      "Basements are either damp or will be damp eventually. This is not pessimism. It is physics. Water vapor moves through concrete. Groundwater pressure pushes against foundations. Basements are habitably damp in ways that upstairs rooms are not.",
      "Moisture management is the first job. Not finishing job number one. Moisture management job number one. If you finish a basement without addressing moisture, you will finish a basement that develops mold, warped walls, and a smell that no air purifier will fix.",
      "Egress requirements apply if you want to call it a bedroom. A bedroom in a basement needs a window that is large enough to climb out of and a path to outside that does not require going through the garage. This adds cost and may not be achievable depending on lot geometry.",
      "Ceiling height matters. Basements often have ductwork, pipes, and beams that hang lower than you want. Options: lower the ceiling, go around with soffits, or budget for moving mechanicals. Each option has a price tag.",
      "The basement is the least expensive room to finish per square foot in some markets and the most expensive in others, depending on moisture conditions, ceiling height, and access. Get a contractor who has actually finished basements in your neighborhood.",
    ],
  }
]

export function getBlogPost(slug: string) {
  return blogPosts.find((post) => post.slug === slug)
}
