export type BlogPost = {
  slug: string
  title: string
  excerpt: string
  category: string
  date: string
  readTime: string
  image: string
  content: string[]
}

export const blogPosts: BlogPost[] = [
  {
    slug: "bathroom-renovation-costs",
    title: "Bathroom Renovation Costs: Where the Money Actually Goes",
    excerpt: "A guided tour of the invoice, from the trades who earn it to the tiles that quietly negotiate with your budget.",
    category: "Bathroom",
    date: "August 8, 2026",
    readTime: "8 min read",
    image: "/images/bathroom-budget.png",
    content: [
      "Ask five renovators how much a bathroom costs and you will get five answers, none of which will match the quote you eventually receive. That is not incompetence. It is the industry's way of preparing you for the fact that a bathroom is a small room with the financial appetite of a yacht.",
      "Labor is where the money actually goes, and it is not close. Waterproofing, tiling, plumbing, and the electrician's cameo appearance all add up faster than the fixtures. The tiles you fell in love with are a rounding error compared to the person who has to cut them around a pipe at 7 a.m.",
      "Demolition looks like the cheapest part until you discover what was hiding behind the old walls. Rotting timber, plumbing that was 'fine' in 1987, and wiring that should have retired decades ago. Budget for the wall to be worse than it looks, because it usually is.",
      "Tiles deserve their own paragraph because tiles are where budgets go to negotiate with themselves. A feature wall in imported tile can cost more than the vanity. The trick is deciding early whether the tile is the star or just the supporting cast, and pricing accordingly.",
      "Fixtures are the visible money. A vanity, tapware, a toilet, and a shower head can range from sensible to 'why does this cost as much as a small car.' The good news is that mid-range fixtures now look like the expensive ones. The bad news is that the expensive ones still cost more.",
      "The hidden costs are where bathrooms earn their reputation. Waterproofing certification, waste removal, a skip bin, and the temporary arrangement where your household shares one bathroom for six weeks. None of these appear on the pretty Pinterest board, and all of them appear on the invoice.",
      "Spend on waterproofing, ventilation, and the things that prevent mold and regret. Save on anything that is purely decorative and easy to change later. A bathroom that works perfectly and looks slightly plain is a success. A bathroom that looks incredible and leaks is a feature film.",
      "The honest math: plan for the quote you received plus ten to fifteen percent for the discoveries your walls have been keeping from you. A bathroom renovation is not a purchase. It is a journey with a very detailed receipt.",
    ],
  },
  {
    slug: "eco-friendly-renovations-save-money",
    title: "Eco-Friendly Renovations That Save Money Long Term",
    excerpt: "Sustainable upgrades that pay you back on the bills instead of asking you to feel good about spending more.",
    category: "Sustainability",
    date: "August 6, 2026",
    readTime: "7 min read",
    image: "/images/eco-friendly.png",
    content: [
      "Sustainable renovation has an image problem. It sounds like something that costs more, takes longer, and results in a house that looks like a very principled cardboard box. The truth is the opposite: the most eco-friendly upgrades are usually the ones that pay you back first.",
      "Insulation is the heavyweight champion of green renovations. It keeps heat in during winter and out during summer, which means your heating and cooling systems get to work less and retire later. Nobody photographs insulation for Instagram, but it is the gift that keeps giving on every single bill.",
      "Water is where small changes compound. Low-flow shower heads, dual-flush toilets, and a heat pump hot water system cut usage without requiring anyone to take a shorter, sadder shower. The planet wins, and so does the water bill, which is a rare alignment of interests.",
      "Lighting is the easiest win in the catalogue. LEDs use a fraction of the power of old bulbs, and sensors in hallways and bathrooms mean lights stop being left on by people who have clearly never looked at an electricity bill. The payback period is measured in weeks, not years.",
      "Passive design is the upgrade you do once and enjoy forever. Shading windows that bake in summer, sealing the drafts that make winter dramatic, and letting the house's own orientation do some of the climate work. It is not glamorous, but it is effective and it never breaks down.",
      "Materials deserve a skeptical eye. A product labeled recycled can still be a poor choice if it needs replacing in five years. Durability is the most sustainable feature a material can have, because the most wasteful renovation is the one you have to do twice.",
      "Eco-friendly renovation is not about making your house a museum of virtue. It is about making choices that are kinder to the planet and kinder to your budget at the same time. That is a rare double win, and it is available in every room of the house.",
    ],
  },
  {
    slug: "kitchen-islands-worth-it",
    title: "Kitchen Islands: Worth It or Wasted Square Meters?",
    excerpt: "How to tell whether your kitchen wants an island or just thinks it does, before you commit to the granite.",
    category: "Kitchen",
    date: "August 4, 2026",
    readTime: "7 min read",
    image: "/images/kitchen-mistakes.png",
    content: [
      "The kitchen island is the most requested feature in renovation history and the most misunderstood. In magazines it hosts beautiful people sipping coffee. In real life it hosts the mail, the homework, the takeaway containers, and one very tired parent leaning on it.",
      "The first question is not 'do I want an island' but 'does my kitchen have the space for one.' The rule of thumb is about 900 to 1200 millimeters of clearance on every side. If you cannot achieve that, the island stops being a feature and becomes an obstacle course.",
      "Clearance is not a suggestion. A kitchen where two people cannot pass each other without performing a choreographed routine will age badly. The island that looked magnificent in the 3D render will feel like a mistake by the third week of actual cooking.",
      "An island earns its square meters by doing real work: extra prep space, storage that does not require spelunking into corner cabinets, and seating that turns the kitchen into a place people actually gather. If your island is only a very expensive table, it is a very expensive table.",
      "Power and plumbing turn a simple island into a project. A sink in the island means running water and waste lines through the floor. Power outlets mean an electrician and careful planning. Both are doable. Both need to be in the budget before the island is in the render.",
      "When islands go wrong, it is usually a space problem. Narrow kitchens, galley layouts, and kitchens that already function as a hallway all make terrible island candidates. The alternative is a peninsula, which delivers most of the benefits without turning the kitchen into a maze.",
      "If you are not sure, start smaller. A movable cart or a compact island can test whether your kitchen actually wants an island or just thinks it does. It is the renovation equivalent of dating before marriage, and it costs considerably less than a divorce from a granite slab.",
    ],
  },
  {
    slug: "renovation-timeline-guide",
    title: "The Renovation Timeline: How Long Will This Actually Take?",
    excerpt: "A field guide to the three timelines of every renovation and which one the invoice will actually follow.",
    category: "Planning",
    date: "August 2, 2026",
    readTime: "8 min read",
    image: "/images/hero-renos101.jpg",
    content: [
      "Every renovation timeline has three versions: the one the contractor quotes, the one the contractor means, and the one your partner repeats to guests with increasing bitterness. This guide is about reconciling all three before you start.",
      "The stages are predictable: design and planning, approvals, quoting, demolition, rough-in of services, and finishes. Each stage has its own pace, and each stage is capable of taking twice as long as the optimistic version printed on the back of a napkin.",
      "Trades quote in ideal conditions. 'Three weeks' means three weeks of straight-line work with materials arriving on time, inspections passing first go, and nobody discovering anything surprising behind the walls. In real life, the walls are full of surprises. That is their hobby.",
      "Material lead times are the quiet assassins of schedules. Tiles, cabinetry, and appliances can take weeks or months to arrive, and they do not care about your deadline. Order everything as early as possible, because a kitchen without its benchtop is a very expensive room for storing boxes.",
      "Approvals and inspections run on their own clocks. Council processes, certifier visits, and the mysterious art of waiting for a signature all take longer than advertised. Build these into the timeline instead of discovering them mid-build and developing new opinions about bureaucracy.",
      "Living through the build adds its own time pressure. A temporary kitchen, dust in every room, and one functional bathroom for a household of four will make the project feel longer than it is. Protect your sanity by protecting the rooms that are not being renovated.",
      "You can compress the timeline, but only in the places that are safe to compress. Lock every design decision before work starts, pay deposits on time, and answer your contractor's questions the same day. The fastest way to speed up a renovation is to stop being the bottleneck.",
      "The realistic formula: take the contractor's estimate and add twenty to thirty percent, then add another week for every room that involves water. If the project finishes early, celebrate quietly and do not mention it to anyone who has renovated before.",
    ],
  },
  {
    slug: "painting-vs-wallpaper",
    title: "Painting vs Wallpaper: A Decision Tree for Every Room",
    excerpt: "The ancient decorating argument, settled room by room, without requiring a seance or a very opinionated stylist.",
    category: "Finishing",
    date: "July 30, 2026",
    readTime: "6 min read",
    image: "/images/hero-renos101.jpg",
    content: [
      "Paint versus wallpaper is the oldest argument in decorating, and the answer is the same as most renovation questions: it depends on the room, the wall, and how much you enjoy future regret. This is the decision tree that settles it.",
      "Paint is the sensible option: affordable, forgiving, and endlessly redoable. It covers mistakes, suits almost every wall, and can be changed on a whim without a therapist. Its only real flaw is that it can be a little predictable, which is exactly what some rooms need.",
      "Wallpaper is the character option: pattern, texture, and the ability to make a room feel intentional in a way paint rarely manages. It also hides imperfect walls better than paint, which is worth knowing if your walls have opinions about being flat.",
      "The decision tree starts with the room's job. Kitchens, bathrooms, and high-traffic hallways get paint, because humidity and sticky fingers are not wallpaper's friends. Bedrooms, dining rooms, and feature walls get wallpaper, because that is where wallpaper's magic actually lands.",
      "The removal question is the one nobody asks until it is too late. Wallpaper is a commitment that outlasts trends, marriages, and sometimes the wall itself. If you rent, redecorate often, or have ever watched someone steam wallpaper off a wall while weeping, choose paint or peel-and-stick.",
      "The compromise that solves most arguments: wallpaper one wall and paint the rest. You get the drama, the texture, and the personality without committing the entire room to a pattern that you will either love forever or be removing in three years while asking yourself what you were thinking.",
    ],
  },
  {
    slug: "kitchen-renovation-mistakes",
    title: "10 Kitchen Renovation Mistakes to Avoid Before Your Toaster Develops Trust Issues",
    excerpt: "A practical guide to avoiding the classic kitchen disasters that turn a tidy remodel into a flour-covered hostage situation.",
    category: "Kitchen",
    date: "April 2, 2025",
    readTime: "8 min read",
    image: "/images/kitchen-mistakes.png",
    content: [
      "Kitchen renovations are popular because everybody wants a beautiful kitchen. They are terrifying because the kitchen is also where the coffee lives, and removing the coffee zone turns ordinary adults into Victorian ghosts by day three. This lesson is the briefing you wanted before the first cabinet came off the wall.",
      "Mistake one is setting a fantasy budget. If your spreadsheet assumes nothing hidden is broken behind the wall, your spreadsheet is not a plan. It is historical fiction. Write a real number for demolition, services, cabinets, benchtops, appliances, splashback, flooring, lighting, and a 15–25 percent contingency. Then stop pretending the last line is optional.",
      "Mistake two is ignoring the work triangle. Sink, cooktop, fridge. A layout that looks incredible on Pinterest but requires twelve steps to get from sink to stove will eventually be judged by someone carrying boiling pasta. Measure clearances. 900–1200 mm of walkway is a kitchen. Less than that is choreography.",
      "Mistake three is buying appliances last. Cabinets, clearances, and services all depend on them. Buying the fridge last is how people discover their dream appliance has the dimensions of a midsize hatchback. Lock the appliance list before the cabinet maker measures. The cabinet maker is not a magician. They are a person with a tape measure and a deposit.",
      "Mistake four is one ceiling light doing the work of a lighting plan. A kitchen should support chopping vegetables, finding cumin, and quietly judging your life choices at 11 p.m. Plan ambient, task, and a little accent. Undercabinet lighting is not decoration. It is how you stop cutting onions in your own shadow.",
      "Mistake five is treating power as an afterthought. Islands need outlets. Bench runs need outlets. Charging, mixers, and the kettle that will live there forever all need a home that is not an extension cord performing a high-wire act. Mark GPOs on the elevation before the electrician roughs in.",
      "Mistake six is storage designed after the pretty doors. Pantry depth, pot drawers, bin pull-outs, and the unglamorous home for the rice cooker decide whether the kitchen works on a Tuesday. If everything pretty has nowhere to live, the benchtop becomes a landfill with a waterfall edge.",
      "Mistake seven is a rangehood that looks like jewellery and extracts like a polite cough. Recirculating units have a use. A proper ducted hood has a career. If you cook, duct it out. If you mostly reheat, be honest with yourself and save the money.",
      "Mistake eight is changing the layout after the services are in. Moving a sink 300 mm after rough-in is how a 'small tweak' becomes a second plumber visit and a new hole in a finished floor. Freeze the wet points early. Write them down. Then stop being interesting.",
      "Mistake nine is skipping the temporary kitchen. A kettle, a microwave, a fridge that still works, and one clean surface will keep the household from staging a coup. This is not luxury. This is operational security.",
      "Mistake ten is signing a vague scope. 'Kitchen renovation' is not a scope. It is a mood. Inclusions, exclusions, who supplies appliances, who does splashback, who does flooring, and how variations get priced should be in writing before anyone owns a sledgehammer. Peel Boss rule: if it is not written down, it will be invoiced later with a smile.",
    ],
  },
  {
    slug: "bathroom-budget-remodel",
    title: "Bathroom Remodeling on a Budget, or How to Spend Less in the Splash Zone",
    excerpt: "Smart ways to improve a bathroom without turning a humble refresh into a tiny tiled money furnace.",
    category: "Bathroom",
    date: "March 28, 2025",
    readTime: "9 min read",
    image: "/images/bathroom-budget.png",
    content: [
      "A tight bathroom budget does not mean the room has to feel sad. It does mean every decision should work hard, because bathrooms are tiny spaces with the financial appetite of a much larger building. This lesson is how you spend the money that actually changes the room, and starve the spending that only changes the invoice.",
      "Keeping the plumbing layout in place is still the biggest saver. Moving a toilet sounds simple until you realize the floor, the waste line, and your bank account all have strong feelings about it. If the toilet, shower, and basin can stay on their current walls, you have already won a round the quote will never advertise.",
      "Spend where people actually notice. Better tapware, lighting, a decent mirror, and a vanity that is not falling apart can do more for the room than imported tile named after an Italian cloud formation. Mid-range tapware in 2026 looks like last decade's luxury. The luxury still costs luxury money.",
      "Waterproofing is not the place you save. In most Australian states it needs a licensed installer and a certificate. That certificate is the document the next buyer's conveyancer will ask for while smiling. Skip it and you have not saved money. You have scheduled a future excavation.",
      "Reduce tile complexity. Every extra niche, feature strip, herringbone field, and fancy cut is labour putting on a cape. A calm large-format tile, one feature wall if you must, and a grout colour that does not show every splash will look more expensive than a mosaic that required a mathematician.",
      "Ventilation is the unphotographed upgrade. A bathroom that cannot exhaust moisture will grow a personality. Size the fan to the room, duct it outside, and put it on a timer so it outlasts the shower. Mould is a budget item that prefers to arrive after you have already spent the budget.",
      "Keep the shower on the existing waste if you can. A new hobless shower is lovely and also a new fall, a new membrane, and a new argument with the floor. If the current tray works and the enclosure is the tired part, replace the screen and the mixer before you invent a wet-room.",
      "Fixtures: buy once, mid-range, and check spare parts. A tap you cannot get a cartridge for in four years is not a bargain. It is a future chase through discontinued catalogues. Write model numbers in a folder. Future-you is not a detective.",
      "The honest bathroom budget has demolition, waste, waterproofing, tiling, plumbing, electrical, fixtures, and a contingency that assumes the wall is worse than it looks. If that total does not fit, shrink the scope. Do not shrink the waterproofing. Peel Boss does not negotiate with water.",
    ],
  },
  {
    slug: "eco-friendly-renovations",
    title: "Eco-Friendly Renovations for People Who Recycle but Also Like Hot Showers",
    excerpt: "How to make smarter, lower-waste renovation choices without acting like sustainability requires misery or beige everything.",
    category: "Sustainability",
    date: "March 25, 2025",
    readTime: "9 min read",
    image: "/images/eco-friendly.png",
    content: [
      "Sustainable renovation starts with keeping good things out of the skip. The greenest cabinet is often the one you did not replace because it lacked 'main character energy.' This lesson is about upgrades that cut waste and bills, not a personality transplant involving hessian.",
      "The biggest wins still come from insulation, sealing drafts, better glazing, and heating or cooling that is sized for the house you have. These are less glamorous than artisanal tiles. They also keep paying rent long after the tiles have stopped being a conversation.",
      "Durability is a sustainability feature. A product that lasts twenty years beats a virtuous-sounding material that retires at the first serious summer. Ask how it cleans, how it fails, and what replaces it. If the answer is 'we are not sure yet,' that is not a material. That is a hope.",
      "Water is the quiet compounding win. A heat-pump hot water system, low-flow fittings that still feel like a shower, and dual-flush toilets cut usage without requiring a family meeting about three-minute hygiene. Comfort and conservation can occupy the same room. It is allowed.",
      "Lighting is the easiest retrofit in the catalogue. LEDs, sensors in halls and bathrooms, and switching that matches how people actually walk through a house. The payback is measured in months. The mood improvement is measured the first evening you can see the bench.",
      "Ask about sourcing and lead times before you fall in love. Recycled, FSC, low-VOC, and locally made options are excellent until they vanish from stock and the builder starts suggesting whatever is available in alarming quantities. Have a second choice written down. Taste is not a supply chain.",
      "Reuse before you replace. Hardware, solid doors, hardwood floorboards, and a vanity that is structurally honest can be refinished. The skip bin does not award points for enthusiasm. It awards a bill.",
      "Passive moves beat gadgets. Shade the west glass, seal the gaps, and let orientation do some of the climate work. A smart thermostat on a leaky house is a very expensive way to watch money leave the building.",
      "This is educational planning, not a green-star certificate. Check local rebate schemes, product warranties, and installer licences for heat pumps and solar. The planet does not need you to become a monk. It needs you to stop renovating the same room twice.",
    ],
  },
  {
    slug: "home-addition-guide",
    title: "How to Plan a Home Addition Without Accidentally Inventing a Very Expensive Shed",
    excerpt: "A grounded guide to planning extra space without losing control of approvals, scope, or your remaining sanity.",
    category: "Planning",
    date: "March 20, 2025",
    readTime: "11 min read",
    image: "/images/hero-renos101.jpg",
    content: [
      "Home additions go wrong when people fall in love with a floor plan before checking whether the site, budget, or local rules are prepared to support that love. This lesson is the planning sequence. Romance can wait until the setbacks are confirmed.",
      "Confirm setbacks, easements, overlays, and heritage or bushfire constraints first. A phone call to council is cheaper than a concept that is legally allowed only if it becomes six percent smaller and emotionally disappointing. Write down what you were told and who told you. Councils are not a hivemind.",
      "Treat the connection to the existing house as a high-risk zone. New work meeting old structure is where surprises gather, compare notes, and invoice you as a group. Floor levels, roof junctions, damp, termite history, and the mystery wall that is 'probably not load-bearing' all live here.",
      "Budget the invisible work. Foundations, drainage, insulation, services upgrades, and making the old house meet the new one will not appear on the pretty render. They will appear on the variation list. A 20 percent contingency on additions is not pessimism. It is literacy.",
      "Plan how people will live during the build. Dust, access, noise, a temporary kitchen, and one bathroom for four humans can become stronger memories than the final room. If you cannot decant the household, you need a staging plan, not a pep talk.",
      "Structure, waterproofing, gas, and regulated electrical are licensed work. This site is educational planning, not a substitute for an engineer, certifier, or your local rules. If someone offers to 'sort the footing without the paperwork,' that is not a saving. That is a future conversation with an insurer.",
      "Lead times will run the diary. Windows, trusses, and stairs do not care that you told the relatives Christmas. Order early, store dry, and check deliveries on the day they arrive. Disputes in month four about a cracked unit from month one rarely go in your favour.",
      "Write a single sentence for 'done.' If you cannot, the addition will keep growing rooms in the night. Scope freeze is how you stop designing a second house while paying for the first one.",
    ],
  },
  {
    slug: "flooring-selection-guide",
    title: "Choosing the Right Flooring for Each Room and Each Slightly Damp Disaster",
    excerpt: "A practical guide to floors that survive real life, including muddy shoes, dripping laundry, and the occasional dropped spaghetti.",
    category: "Flooring",
    date: "March 15, 2025",
    readTime: "9 min read",
    image: "/images/hero-renos101.jpg",
    content: [
      "Flooring choices should be based on moisture, impact, cleaning, and your household's proven commitment to walking indoors like a herd of decorative buffalo. Looks come second. A beautiful floor that fails in year two is just a delayed invoice.",
      "Bathrooms and laundries need water tolerance first, and a membrane under the finish that someone will certify. Kitchens need something that handles spills, grit, and the emotional violence of a full jar of passata. Hallways need durability. Bedrooms can afford warmth and quiet.",
      "Read the substrate before you read the brochure. A slab that is not dry enough, a timber floor that moves, or a levelling compound that was a suggestion will announce themselves through any finish. Moisture meters exist. Use one before you glue anything you like.",
      "Timber and timber-look are not the same job. Solid hardwood can be sanded and has opinions about bathrooms. Engineered can be more stable. Laminate is affordable and unforgiving of standing water. Luxury vinyl plank is the current workhorse for wet-adjacent rooms if the product and the install method match the room.",
      "Tile is honest. It is cold, durable, and only as good as the bed underneath. Hollow tiles pop. Tiny edge slivers look like a dare. Dry-lay the room, aim for cuts over 50 mm, and pick a grout you are willing to live with after the first muddy winter.",
      "Carpet still belongs in bedrooms if you want the room to feel like a room and not a departure lounge. Underlay is not a place to save two dollars a metre. The carpet will feel and last like the underlay you bought, not the one you meant to buy.",
      "Warranties are allergic to the wrong install. Compare the warranty to the real substrate, the adhesive, the underlay, and the wet-area rules. Many 'product failures' are communication failures wearing a timber-look costume.",
      "Acclimatise timber and vinyl in the room. Leave the expansion gap. Do not pin a floating floor to the wall because a gap makes you nervous. The gap is how the floor stays flat in February. Skirting exists to cover your anxiety.",
      "Peel Boss rule: choose the floor for the worst day in that room, not the photoshoot. Mud, kids, dogs, and a leaking planter are the exam. The showroom is just the brochure.",
    ],
  },
  {
    slug: "diy-vs-professional",
    title: "DIY vs. Professional: A Helpful Guide to Knowing When Confidence Is Not a Qualification",
    excerpt: "How to decide which jobs you can handle yourself and which ones deserve a licensed adult with insurance.",
    category: "DIY",
    date: "March 10, 2025",
    readTime: "9 min read",
    image: "/images/hero-renos101.jpg",
    content: [
      "DIY works when the task is low-risk, repetitive, and inspectable. Painting, protection, demolition planning, simple furniture assembly, and a lot of prep are reasonable. Rewiring a switchboard because you watched three confident videos at midnight is a different sport. This lesson is the sorting hat, not a dare.",
      "Bring in licensed trades for waterproofing, structure, gas, and regulated electrical. These are not the categories where you want to discover a hidden talent for consequences. In most Australian states, unlicensed work in those areas can void insurance and fail a sale. That is planning information, not legal advice. Check your state.",
      "The hybrid model is how most sane renovations finish. Owners handle planning, procurement, masking, painting, hardware, and the unglamorous tidy-up. Professionals handle the systems behind the walls and the certificates that prove it. Your time is a resource. So is your sleep.",
      "Ask one question before you pick up a tool: if I get this wrong, does another trade have to undo it before they can start? If yes, hire earlier. Cheap advice at the right moment is cheaper than the phrase 'while we're here' said by a person holding a saw.",
      "Demo is seductive and also where asbestos, live services, and load paths like to introduce themselves. Pre-1990 houses get tested before they get smashed. Isolate power, water, and gas properly. Photograph everything. Enthusiasm is not a method of isolation.",
      "Painting, sanding, and cosmetic carpentry reward patience more than talent. Measure, mask, prime, and do the extra coat. A weekend warrior can produce a professional-looking wall. A weekend warrior cannot produce a professional-looking waste pipe.",
      "Write a split list: owner tasks, licensed tasks, and 'ask first' tasks. Put it on the fridge. When a job drifts from one column to another, that is a meeting, not a vibe. Intel Academy bar: confidence is a feeling. A licence is a document.",
      "If you are tired, stop. Most DIY disasters happen in the last hour of a long day, when the 'one more cut' energy arrives. The timber will still be there in the morning. Your fingers would like to be as well.",
    ],
  },
  {
    slug: "paint-colors-guide",
    title: "How to Choose Paint Colors Without Eventually Choosing 'Some Kind of Beige'",
    excerpt: "A survival guide for anyone who has ever stood in a hardware store for 47 minutes holding sample chips and feeling feelings.",
    category: "Design",
    date: "March 5, 2025",
    readTime: "9 min read",
    image: "/images/hero-renos101.jpg",
    content: [
      "Paint is the cheapest way to transform a room and the fastest way to regret a personality. The difference is testing. Sample pots on actual walls, not a 30 mm chip held under a fluorescent tube that has never loved anyone.",
      "Natural light changes the brief. The colour you approved at noon will moonlight as something else at 4 p.m. when the room starts looking like a cave with opinions. Test on two walls. Live with the patches through a weekday and a weekend.",
      "Undertones are the entire plot. One 'warm white' has yellow. One has pink. One has grey and will make your timber look sick. If three colours look the same, they are not. Look again at dusk. One of them is lying.",
      "Map sheen to the job. Ceilings want flat. Walls in living rooms want low sheen. Trims and doors want a harder enamel that can be wiped. Kitchens and bathrooms want a washable finish that does not turn every splash into a permanent record.",
      "Prime when the wall asks for it. New plaster, stain bleed, a dark-to-light change, or a glossy oil that you want to cover with water-based paint — these are primer jobs. Skipping primer is how a 'two-coat' job becomes a four-coat apology.",
      "Commit for a week after the first real coat, not the first wet roller. Paint looks different wet, different on day two, and different when the furniture comes back and steals half the light. Panic is not a colour strategy.",
      "Whole-house palettes beat room-by-room shopping. One main wall colour, one trim, one ceiling, and one accent you can defend in writing. More than that and the house looks like it could not make a decision and decided to document the process instead.",
      "If you are still stuck, paint the smallest room first. A mistake in a powder room is a morning. A mistake in an open-plan living area is a long weekend and a new personality. Peel Boss does not pick a hero colour in the aisle. Peel Boss takes the chips home and interrogates them.",
    ],
  },
  {
    slug: "lighting-fundamentals",
    title: "Lighting 101: Why Your Kitchen Has One Light and Your Dreams Have None",
    excerpt: "Understanding layers, lumens, and why changing a lightbulb is not a personality but it should be.",
    category: "Design",
    date: "February 28, 2025",
    readTime: "9 min read",
    image: "/images/hero-renos101.jpg",
    content: [
      "Good lighting is invisible. You notice it when it is missing, or when you walk into someone else's house and everything looks annoyingly competent. This lesson is how you stop asking one tired ceiling light to do three jobs.",
      "Three layers beat one. Ambient light so the room exists. Task light on benches, desks, and mirrors. Accent light for the shelf you actually styled. One downlight grid on full bright is a waiting room. It is not a plan.",
      "Draw the lighting plan before the electrician roughs in. Switching arrangements are archaeology after the plaster. Mark what turns on from the door, what the island needs, and whether the rangehood light is doing secret overtime.",
      "Undercabinet lighting is not optional in a working kitchen. It was optional when people cooked less and ordered more. We have evolved. A warm strip under the wall cabinets makes the bench usable and makes the room look finished without shouting.",
      "Colour temperature is a mood decision pretending to be a technical one. 2700K is warm and evening. 3000K is a reasonable whole-house compromise. 4000K is alert and a bit clinical. 5000K is for garages and people processing invoices. Do not mix them in one sightline unless you enjoy the house looking confused.",
      "Dimmers are cheap insurance. A living room that can go from homework to dinner without a personality change is a room people stay in. Specify dimmable fittings and compatible drivers. A dimmer on a non-dimmable LED is a strobe with extra steps.",
      "Bathrooms need light on faces, not just on tiles. A mirror with side or well-placed front light beats a single downlight that turns every human into a raccoon. Put the fan on a timer. Put the lights on a switch you can find at 2 a.m.",
      "Exterior lighting is safety first, theatre second. Paths, steps, and the lock on the front door need to be seen. The string lights can come later. If the neighbour can read by your floodlight, you have not designed lighting. You have declared a border.",
    ],
  },
  {
    slug: "cabinet-selection-guide",
    title: "Cabinet Selection: Why IKEA Is Sometimes Right and Custom Is Sometimes a Trap",
    excerpt: "A completely practical guide to cabinets that does not judge you for whatever you choose, but does judge the decisions that lead to regret.",
    category: "Kitchen",
    date: "February 22, 2025",
    readTime: "10 min read",
    image: "/images/kitchen-mistakes.png",
    content: [
      "Cabinets are the most expensive decision in most kitchens. The gap between a good run and a foolish one is usually a few thousand dollars and one argument about shaker doors. This lesson is how you pick a system that survives humidity, kids, and the dishwasher.",
      "Modular systems (IKEA and its cousins) are underrated and correctly rated. The price is real. The hardware can be annoying. The finished result, with decent doors and a proper benchtop, is frequently indistinguishable from cabinets that cost three times more — if the kitchen is a standard shape.",
      "Custom earns its keep when the room is not a rectangle, the walls are not plumb, or you need unusual depths, appliance housings, or a pantry that is actually a room. Paying custom money for a straight galley that a modular system could have done is how budgets go to finishing school and fail.",
      "Boxes matter more than door style. Plywood carcasses outperform cheap particleboard near dishwashers and sinks. Soft-close hinges are not a luxury in 2026. If a door slams, the kitchen sounds like it is still arguing with you.",
      "Measure appliances before anyone draws a cabinet. Fridge depth, dishwasher height, and the oven that wanted to be a statement will not shrink to fit a pretty elevation. The cabinet maker is building around objects. Give them the objects.",
      "Drawers beat doors for pots, plates, and the graveyard of lids. Deep drawers at the cook's hip save more marriages than a feature island. Corner units need a plan: a LeMans, a lazy Susan, or an honest decision to store the stuff you never use.",
      "Handles, height, and kickboards are the details people touch every day. Decide them in the room, not on a laptop. A handle that catches a hip will be famous for the wrong reason.",
      "Install is where flatpack becomes furniture. Level the bases, pack the walls, and spend time on door alignment. Rushing this is how a reasonable cabinet starts looking like it was hung during an aftershock.",
      "Peel Boss rule: pick the cabinet system for the room you have, not the showroom you visited. If the quote for custom is mostly doors, ask what the boxes are made of. The doors are the outfit. The boxes are the skeleton.",
    ],
  },
  {
    slug: "window-selection-guide",
    title: "Windows: The Part of Your House That Costs Too Much and Does Too Much",
    excerpt: "Understanding U-values, SHGC, and why the window salesperson knows more than you do but maybe not in a helpful way.",
    category: "Planning",
    date: "February 18, 2025",
    readTime: "9 min read",
    image: "/images/hero-renos101.jpg",
    content: [
      "Windows are sold on metrics that sound like an engineering elective. U-value is heat transfer. SHGC is solar heat gain. Together they tell you whether the glass will work in your climate or just look expensive while the air-con does overtime.",
      "In most of Australia, double glazing is the sensible default for replacements. Triple glazing is for alpine nights or people who enjoy invoices. Match glass to orientation: west sun is a different problem to a shaded south wall.",
      "Frame material is a maintenance contract. Aluminium is slim and strong. Thermally broken aluminium behaves better. uPVC is low-maintenance. Timber is beautiful and a commitment. Do not pick a frame because it photographed well in a Scandinavian loft that does not have your western sun.",
      "Installation is where windows fail. A perfect unit in a crooked opening, with the flashings in the wrong order, will leak air and then water and then trust. Sill flashing first, then sides, then head. Reverse that order and you have built a funnel.",
      "Order early. Custom windows are often 6–12 weeks. A carpenter standing around waiting is on your tab. Measure twice, confirm the reveal, and check the delivery against the order before anyone signs the docket.",
      "Bigger is not always better. More glass is more heat, more glare, and sometimes more of the neighbour's recycling. Placement and shading do as much work as the specification sheet. A smaller window in the right wall beats a cinema screen in the wrong one.",
      "Safety glass, egress, and bushfire ratings are not style choices. If a bedroom needs a window you can climb out of, the opening size is a rule, not a vibe. Check your local code and the certifier. This is orientation, not a compliance certificate.",
      "Budget the flashings, reveals, architraves, and making-good. The unit price in the brochure is not the installed price. Peel Boss does not buy a window because the salesperson said 'it will pay for itself' without asking in which decade.",
    ],
  },
  {
    slug: "hvac-renovation-guide",
    title: "HVAC: The System You Ignore Until It Makes a Sound That Sounds Like a Sound Nothing Should Make",
    excerpt: "A practical guide to heating and cooling that will not make you an expert but will make you a less confused person.",
    category: "Systems",
    date: "February 12, 2025",
    readTime: "11 min read",
    image: "/images/hero-renos101.jpg",
    content: [
      "Heating and cooling is complicated in proportion to how much you rely on it. A temperate suburb can live on a couple of splits. A house with real summers and real winters needs a plan, not a catalogue page. This lesson is how you brief a licensed technician without nodding along to jargon.",
      "Sizing matters more than brand. An oversized unit short-cycles, wastes power, and dies early. An undersized unit runs forever and still loses in February. Ask for a proper heat-load calculation, not a guess based on floor area and optimism.",
      "Choose the system for the house you have. Splits are honest for a few rooms. Ducted is whole-house comfort if the ceiling can take the ducts. Hydronic is lovely and slow and expensive to retrofit. Multi-head systems are a compromise with a lot of wall jewellery.",
      "Ductwork is underrated. New equipment on tired, leaky, uninsulated ducts will underperform and then get blamed. The ducts deliver the comfort. The outdoor unit manufactures it. Both have to work. If the ceiling is open, this is the moment.",
      "Put the outdoor unit where it can be serviced, where it will not cook a bedroom window, and where the neighbour will not start a petition. Clearance is not optional. Leaves, dogs, and decorative pots are not a condenser enclosure.",
      "Zoning stops the thermostat wars. Sleeping rooms and living rooms want different evenings. A zone plan is cheaper than a second system and more peaceful than a family group chat about 21 versus 23.",
      "Refrigerant work, gas heating, and electrical isolators are licensed jobs. DIY 'top-ups' are how small problems become environmental and legal ones. This site will not walk you through charging a system. It will tell you to book the person who can.",
      "Maintenance is boring and cheaper than January. Filters every one to three months. A professional service once a year. Clear the outdoor coil. The emergency call-out costs more than the service visit you skipped because the weather was nice.",
      "If you are renovating, run the HVAC decision in parallel with framing, not after the plasterer has gone. Ducts, drains, and condensate lines hate being an afterthought. Intel Academy bar: comfort is a system. A pretty controller is just the remote.",
    ],
  },
  {
    slug: "outdoor-living-spaces",
    title: "Outdoor Living: How to Turn Your Backyard Into a Place Adults Actually Want to Be",
    excerpt: "Because the deck is for holding plants and the BBQ is for the one day a year it rains.",
    category: "Outdoor",
    date: "February 5, 2025",
    readTime: "9 min read",
    image: "/images/hero-renos101.jpg",
    content: [
      "Outdoor living is not a furniture catalogue. It is zones, shade, drainage, and a reason to go outside that is not 'the indoor bin is full.' This lesson is how you stop the backyard from judging you through the sliding door.",
      "Define the zones before you buy a six-seater. Lounge, cook, dine. Each needs space to function. Cramming a dining table onto a patio meant for four is how Sunday lunch becomes a logistics exercise. Measure, then shop.",
      "Shade is non-negotiable in most of Australia. Umbrellas move. Pergolas stay. A sail needs fixing points that are actually structural. Direct western sun will empty the deck faster than a group chat about whose turn it is to cook.",
      "Levels and drainage come before paving. Fall away from the house. A pretty courtyard that ponds after rain is a water feature you did not order. Compact the base. The surface is the costume. The base does the work.",
      "Materials outdoors have a harder job than materials indoors. UV, rain, salt, and the temperature swing that makes cheap timber look tired in one summer. Ask what survives your postcode, not what survived a styled photoshoot in another climate.",
      "Cooking outdoors needs power, a level pad, and a conversation about smoke. A BBQ against a timber screen is a mood until it is a mark. Check clearances. Keep a hose that is not decorative.",
      "Lighting extends the evening. Path lights stop the trip to the tongs becoming a thriller. Warm ambient light beats a single flood that interrogates the salad. Put exterior fittings on weather-rated circuits. Indoor pendants hanging from a pergola will learn about weather the hard way.",
      "Council rules still apply to structures, decks over a certain height, and anything that looks like a roof. This is planning, not a permit. If the pergola is more than a suggestion, ask before you pour.",
      "Peel Boss rule: build the outdoor room for the twelve weeks you will actually use it, not the twelve photos you will take once. Comfort, shade, and a surface that drains will outlast the egg chair.",
    ],
  },
  {
    slug: "small-bathroom-solutions",
    title: "Small Bathroom Solutions: Making Tiny Spaces Feel Less Like You Are Renovating a Bus Bathroom",
    excerpt: "Spatial illusions, fixture choices, and the subtle art of not hating your only bathroom.",
    category: "Bathroom",
    date: "January 28, 2025",
    readTime: "9 min read",
    image: "/images/bathroom-budget.png",
    content: [
      "Small bathrooms are not small problems. They need the same waterproofing, the same ventilation, and the same desire not to feel like a cupboard, all in less space. This lesson is tactics, not magic.",
      "Keep the plumbing on the existing walls if you can. In a tiny room, moving a toilet 200 mm can cost more visual space than it buys and will definitely cost money. Spend the save on a better screen and a vanity that is not a boat.",
      "Wall-hung fixtures earn their keep. A floating vanity or wall-hung toilet does not add square metres. It adds visible floor, which the eye reads as room. You will need blocking in the wall. Decide that in framing, not at fit-off.",
      "A clear glass shower screen beats a curtain in almost every small bathroom. A curtain shrinks the shower and then attacks you. A fixed panel or a well-hung pivot keeps the sightline. Keep the tray simple. A mosaic floor in a 900 mm shower is a lot of grout in a very small argument.",
      "One large mirror works harder than two clever ones. It doubles the light and the room. Recess a cabinet if you can. Surface clutter is how small bathrooms start feeling like a chemist's shelf.",
      "Storage is a honesty test. A pedestal basin looks airy and then has nowhere for the spare toilet paper. A slim vanity with drawers will make the household kinder. If you truly have no depth, a recessed niche and a decent cabinet over the cistern will do more than a ladder shelf of products.",
      "Light the face, exhaust the steam, and use a larger tile with fewer grout lines. A dark, busy floor in a tiny wet room is a mood. It is rarely a good one. A light, continuous floor and a quiet wall tile will make the room feel finished instead of busy.",
      "Doors matter. A swinging door that hits the vanity is a daily tax. A cavity slider is a gift if the wall can take it. If it cannot, reverse the swing or use a narrower door before you buy a smaller basin you will hate.",
      "Waterproofing and ventilation still run the show. A small bathroom that leaks is not charming. It is a large problem in a small box. Certificates, falls, and a fan that actually leaves the building are the unglamorous pass marks.",
    ],
  },
  {
    slug: "storage-solutions-guide",
    title: "Storage Solutions That Do Not Require a Pinterest Board or a Shed",
    excerpt: "Because every house has enough stuff and not enough places for the stuff. This is a universal law, like gravity but worse.",
    category: "Organization",
    date: "January 20, 2025",
    readTime: "8 min read",
    image: "/images/hero-renos101.jpg",
    content: [
      "Storage is never enough. Renovation can improve the ratio. It cannot repeal the law that stuff expands to fill the house. The goal is homes for the things you actually keep, so the living rooms can go back to being rooms.",
      "Declutter before you draw a single cabinet. Adding storage without removing dead inventory is filling a bath with the drain open. Sort stay / go / maybe. The maybe pile is usually go after two weeks of not missing it.",
      "Use height. Tall joinery, the unused wall above a door, and garage overhead racks take volume that floor furniture wastes. If you cannot reach it without a stool, it is archive storage. Label it like you will not remember.",
      "Built-ins beat a showroom of matching boxes in most rooms. A window seat with a lid, a full-height pantry, and robes to the ceiling use the awkward leftover space that freestanding furniture politely ignores. They cost more. They also look like the house meant it.",
      "Kitchens want drawers for daily tools and a pantry that is not a black hole. Halls want a drop zone that is not the dining table. Bedrooms want robes with a real hanging-to-shelf ratio, not a rail and a dream.",
      "The laundry, garage, and linen cupboard are where houses hide their shame. One wall of labelled tubs will save more marriages than a walk-in pantry that only holds cereal. Design those rooms as rooms, not leftovers.",
      "Do not store moisture-sensitive things against a cold external wall without a plan. Condensation does not care that the box said 'archival.' Keep gaps, use breathable boxes, and keep the really important paper inside the conditioned part of the house.",
      "Peel Boss rule: storage is a system, not a purchase. If every object does not have a return address, it will emigrate to the bench. Build the address first. Then you may buy the pretty baskets.",
    ],
  },
  {
    slug: "energy-efficiency-retrofit",
    title: "Energy Efficiency Retrofits: Lower Bills, Warmer House, Fewer Excuses",
    excerpt: "A practical guide to making an older home perform better without turning it into a museum of good intentions.",
    category: "Sustainability",
    date: "January 15, 2025",
    readTime: "10 min read",
    image: "/images/eco-friendly.png",
    content: [
      "Energy retrofits are the highest-return work most renovators skip so they can argue about tapware. Comfort improves. Bills drop. The house stops leaking money through gaps you cannot photograph. This lesson is the order of operations.",
      "Seal first. Air leaks around windows, doors, ceiling penetrations, downlights, and the 'temporary' hole someone never closed. A cold day and a smoke pencil will teach you more than a brochure. Seal, then insulate. Insulating a wind tunnel is a hobby.",
      "Ceiling insulation is usually the biggest single win because heat is an opportunist. R4 to R5 in many Australian roofs is a common target — check your climate zone rather than copying a forum. Do not compress batts. Compressed insulation is just an expensive cushion.",
      "Walls are harder and still worth planning when a room is already open. If the plaster is coming off, put the batts in. If it is not, there are still options, and they all cost more than doing it while the wall is a cavity. Underfloor insulation on a suspended floor is the cheapest cold-toes fix in the book.",
      "Windows are the controversial spend. Replacement helps when the units are truly tired. If they are decent, seals, pelmets, and shading often beat a full swap on payback. Do not replace windows to avoid sealing the rest of the house. That is buying jewellery for a draft.",
      "Hot water, heating, and cooling are the systems that show up on the bill. A heat-pump hot water system, a correctly sized split or ducted unit, and a fridge that is not auditioning for a runway all matter. Get licensed installers. Rebates exist in some states. They also expire. Check, do not assume.",
      "Lighting and behaviour are the cheap last mile. LEDs, sensors, and not heating a hallway nobody sits in. A smart thermostat in a leaky house will give you beautiful graphs of waste.",
      "This is educational planning, not an energy rating. If you need a formal assessment for a sale or a rebate, hire the assessor. Intel Academy bar: the greenest kilowatt is the one the house no longer has to buy.",
    ],
  },
  {
    slug: "laundry-room-renovation",
    title: "Laundry Room Renovation: Making the Room You Cannot Escape Slightly Less Torturous",
    excerpt: "Because doing laundry is already unpleasant enough without the room actively contributing to your misery.",
    category: "Laundry",
    date: "January 8, 2025",
    readTime: "9 min read",
    image: "/images/hero-renos101.jpg",
    content: [
      "The laundry is the room nobody renovates until it starts renovating itself with mould, a bouncing machine, and a tap that weeps. Then it becomes the most important room in the house, because nobody can agree on what 'delicates' means. This lesson is how you make it a room instead of a corridor with a hose.",
      "Location is luck. Near bedrooms is a gift. At the back of a garage is a commute. If you can move it, you are in addition territory — permits, falls, and a new waste. If you cannot, improve the room you have. Most households need function more than they need a new postcode for the socks.",
      "A bench is not optional. Folding on a dryer lid is how clean clothes become a landscape. A continuous benchtop over front loaders, with a tap and a tub if you can keep them, turns the room into a workstation. Height matters. Your back will file a report.",
      "Waterproof the wet zone properly. Laundries splash, overflow, and occasionally produce a hose that has opinions. A membrane, a hob or a fall to a drain, and a floor that can cope are planning items, not decorations. Check what your state expects. Certificates still matter at sale.",
      "Storage wants doors. Detergent, the mystery backlog of hangers, and the bucket of 'useful' bits will colonise open shelves and then look like a hardware aisle. Tall joinery, a broom cupboard, and a rail for hanging wet shirts will do more than a pretty tile splashback.",
      "Machines need a level, a drain, isolation taps you can actually reach, and a power circuit that is not shared with a hairdryer on another continent. Anti-vibration pads are cheaper than an argument with the floor below. Leave service space. A machine you cannot pull out is a machine you will dread.",
      "Vent the dryer outside if it is a vented dryer. Condenser and heat-pump dryers still want a room that can breathe. A sealed laundry with a dryer is a moisture factory. Pair it with an exhaust fan on a timer, the same way you would a bathroom.",
      "Light the bench and the sorting zone. One dusty batten is how navy and black start a relationship. A washable wall finish and a floor you can mop will outlast any feature tile you briefly loved.",
      "Peel Boss rule: design the laundry for a sick-week load, not a catalogue Tuesday. If it works when everyone is tired and the pile is hostile, it works.",
    ],
  },
  {
    slug: "garage-renovation-guide",
    title: "Garage Conversions: The Space You Have Been Wasting on Things You Said You Would Sort",
    excerpt: "A garage full of boxes labeled 'miscellaneous' is not storage. It is a shrine to good intentions that stopped at the door.",
    category: "Garage",
    date: "January 3, 2025",
    readTime: "10 min read",
    image: "/images/hero-renos101.jpg",
    content: [
      "Garages hold the car (sometimes), the stuff (always), and a workshop that will be finished 'after this project.' Converting one to living space is a real renovation, not a paint job with a sofa. This lesson is how you decide whether the conversion is a plan or a very expensive shed with feelings.",
      "Treat it like a room. Insulation, a weather-tight envelope, a floor that is not a slab sweating through a rug, lighting, and heating or cooling. A garage that remains a garage in winter will make a terrible bedroom in July.",
      "Parking versus living is the first trade. If the car has somewhere else legal and dry, the conversation is simpler. If this is the only covered space, you are trading paint fade and hail for a room. Some buyers care. Write that down before you fall in love with a floor plan.",
      "Check planning rules, fire separation, ceiling height, light, ventilation, and egress if you want to call it a bedroom. This is educational orientation, not a permit. Councils and certifiers still run the show. Garage conversions that skip this step become 'the room we cannot mention in the listing.'",
      "The slab, the door, and the damp are the usual villains. Floor level may sit below the house. The big door is a hole you have to turn into a wall. Garages were not designed as habitable rooms. Moisture, termites, and the cold coming through an uninsulated tilt door will all file reports.",
      "Services need a proper run: power, data, smoke alarms that meet current rules, and possibly plumbing if you have invented an ensuite. Do not extend a lighting circuit with hope. Licensed electrical and, if needed, plumbing.",
      "Budget the boring line items. Removing the door, framing the opening, insulation, plaster, new windows, and making the outside look like it always meant this. The 'we will just line it' quote is the first chapter, not the book.",
      "If you only need storage and a workbench, a conversion may be the wrong project. Industrial shelving, a sealed floor, insulation in the ceiling, and lighting you can work under will cost less than a habitable room and still make the space useful. Peel Boss does not convert a garage to avoid sorting the boxes.",
    ],
  },
  {
    slug: "home-office-renovation",
    title: "The Home Office Renovation: Because Your Kitchen Table Has Heard Enough About Spreadsheets",
    excerpt: "A guide to building a workspace that supports productivity without convincing your household you have built a second office and will now be unavailable for all chores.",
    category: "Office",
    date: "December 28, 2024",
    readTime: "9 min read",
    image: "/images/hero-renos101.jpg",
    content: [
      "A corner of a bedroom is a desk. It is not an office. The last few years proved that households need a door that closes and a surface that is not also dinner. This lesson is how you build a room that works without declaring independence from the chores.",
      "Location beats size. A small room with a door and a window beats a handsome alcove on the living-room thoroughfare. If every kettle and cartoon becomes your soundtrack, you do not have a workplace. You have a set.",
      "Put the desk where glare does not win. Side light is kinder than a window in the monitor. Face a wall if you need focus. Face the room if you need to see who is approaching with a question about snacks. There is no perfect chair position. There is a less bad one. Test it for a week with painter's tape before you buy joinery.",
      "Power and data are the bones. Ethernet still beats hoping the wifi respects you. Two double GPOs at desk height, cable management that is not a nest, and a surge-protected board will save more hours than a designer lamp. Run the cable while the wall is open. Retrofit is archaeology.",
      "Storage in an office is paper, gear, and the objects that migrate from other rooms because this one has a door. Built-in shelves to the ceiling beat a tribute to mismatched cubes. A closed cupboard hides the printer, which is not a personality.",
      "Acoustic manners matter. Soft finishes, a solid door, and weather-stripping around the jamb do more for calls than a ring light. If you share a wall with a bathroom or a teenager, acoustic batts in that wall are a professional courtesy to your own career.",
      "Lighting: ambient plus a task lamp. A single downlight on a shiny screen is how you age in fast-forward. 3000K is a reasonable working compromise. Save 4000K for the garage.",
      "If the only space you have is a bedroom, zone it. A screen, a rug, and a desk that can close will not fool anyone, but they will help you stop working from the pillow. The house will still know. You will mind less.",
      "Peel Boss rule: design the office for a bad Tuesday, not a productivity reel. If it works when the household is loud and the deadline is real, it is an office.",
    ],
  },
  {
    slug: "hvac-maintenance-guide",
    title: "HVAC Maintenance: The System You Ignore Until It Makes a Sound That Sounds Like a Sound Nothing Should Make",
    excerpt: "A practical guide to keeping your heating and cooling system running efficiently before it becomes a very expensive emotional event.",
    category: "Systems",
    date: "December 20, 2024",
    readTime: "8 min read",
    image: "/images/hero-renos101.jpg",
    content: [
      "Heating and cooling have two seasons and one personality: they fail just after you needed them. Most of those failures were available for prevention in the shoulder season. The shoulder season is now. This lesson is the homeowner half of the job. The refrigerant half belongs to a licensed technician.",
      "Filters are the one habit that changes everything. Every one to three months, depending on dust, pets, and how much demolition you did without taping the returns. A clogged filter makes the system work harder and the air taste like a cupboard. Write the size on the inside of the unit door so you stop guessing in the aisle.",
      "Clear the outdoor unit. Leaves, grass, and the occasional tenant who does not pay rent all like the warm box. Keep a clear buffer. Do not blast it with a pressure washer like it insulted you. A gentle rinse and a fin comb if you know what you are doing. If you do not, book the service.",
      "Listen. New rattles, short cycling, ice on the pipes, or a room that never quite gets there are not quirks. They are tickets. Catching them in April is cheaper than catching them in a heatwave when every technician is a celebrity.",
      "Thermostats still run on batteries in too many houses. Check them when you change clocks. A blank thermostat in July is a very specific kind of silence.",
      "Book a professional service once a year. They will check charge, drains, electrics, and the things that are not visible from the hallway. This is not upselling. This is how you avoid the after-hours rate.",
      "If you renovated, change the filters again after the dust settles. Construction dust is how a new system inherits an old death. Rangehood and AC filters both count.",
      "Peel Boss rule: the cheapest kilowatt is the one a clean filter did not waste. The second cheapest is the service visit you did not skip because the weather was fine.",
    ],
  },
  {
    slug: "plumbing-basics",
    title: "Plumbing Basics: What Every Homeowner Should Know Before Calling a Plumber",
    excerpt: "Save money and embarrassment by knowing the difference between a pipe and a problem.",
    category: "Plumbing",
    date: "December 15, 2024",
    readTime: "9 min read",
    image: "/images/bathroom-budget.png",
    content: [
      "Every household needs to know where the main water shutoff is, and whether it actually works. Test it once on a calm Saturday. Label it. A burst pipe does not wait for you to invent a filing system. This lesson is orientation, not a licence to rebuild the stack.",
      "Time is the difference between an inconvenience and a claim. A running toilet is a bill. A burst or a ceiling stain that grows while you 'keep an eye on it' is a renovation. Shut the water, catch what you can, and then call. Photographs help the insurer. Towels help the floor.",
      "Skip the hero drain chemicals. They sometimes work and sometimes eat the pipe you still need. Plunger, then a hand snake, then a licensed plumber with a proper machine. If more than one fixture is slow, the blockage is not in the plug. It is in the line.",
      "Flush waste and toilet paper. Everything else is a future invoice with a smell. 'Flushable' wipes are a marketing story. Your pipes did not sign it.",
      "Know the isolation valves under sinks and behind the washing machine. When a hose fails, the main tap is a long walk. A valve that has not been turned in a decade may need a plumber just to move. That is still cheaper than a flooded cabinet.",
      "Hot water systems have pressure-relief pipes and drip trays for a reason. A steady drip from the relief may be a valve or a temperature problem. A dry tray that suddenly fills is a conversation. Licensed gas and electrical work stays licensed.",
      "Outside, taps, irrigation, and the hose that was 'temporary' in 2019 all freeze or split depending on your climate. Lag the exposed pipe. Turn off and drain irrigation if your winter requires it. A split poly line will find the one day you are away.",
      "When you renovate, pressure-test before plaster. Find leaks when the wall is still a cavity. After tiles, every drip is archaeology. Peel Boss does not caulk a mystery. Peel Boss finds the joint.",
    ],
  },
  {
    slug: "electrical-safety",
    title: "Electrical Safety: When to Call an Electrician and When to Feel Proud of Yourself",
    excerpt: "A guide to knowing the difference between a safe DIY electrical job and a future story about how the house almost burned down.",
    category: "Electrical",
    date: "December 10, 2024",
    readTime: "8 min read",
    image: "/images/hero-renos101.jpg",
    content: [
      "Electrical work has one planning rule: when in doubt, stop. Guessing is not a method. The cost of being wrong is not a new switch. It is fire, shock, and an insurer who would like to see a certificate. This lesson is how to know what you may brief and what you must book.",
      "In Australia, most new circuits, switchboard work, and anything beyond a like-for-like fitting is licensed electrical work. Rules vary by state. This is not a how-to for wiring. It is a briefing so you do not treat a YouTube video as a qualification.",
      "Warning signs are not quirks. Flicker, warm plates, a burning smell, breakers that trip for sport, or lights that dim when the kettle boils are tickets for a licensed electrician. 'It has always done that' is not a diagnosis. It is a delay.",
      "If you are renovating, plan circuits per room, not per appliance you remember today. Kitchens want several. Wet areas want the right safety switches. Data and smoke alarms are easier while the walls are open. Mark heights with tape on the studs. Tape moves. Cable does not enjoy it.",
      "Outdoor fittings need outdoor ratings. An indoor batten on a patio is how weather writes a report. Use the right IP rating, the right isolator for the AC, and a person who will test and tag the safety switch at the end.",
      "Old houses hide surprises: cloth cable, unearthhed metal, and junction boxes that were a suggestion. If the plaster is off, photograph and ask. Replacing a few points on tired cable can become a partial rewire. Budget the possibility. Pretending it is 'just a few GPOs' is how the quote grows a second act.",
      "You can still do the non-licensed half well: isolate at the board if you have been shown how, keep the area dry, leave access, and do not bury cables under insulation in ways that cook them. When the electrician arrives, have the lighting plan printed. They are not paid to read your mind.",
      "Peel Boss rule: electricity is not the place you prove you are handy. It is the place you prove you can hire. Keep the certificates. The next sale will ask.",
    ],
  },
  {
    slug: "attic-renovation",
    title: "Attic Renovations: Adding Space Without Adding a New Foundation",
    excerpt: "How to evaluate whether your attic can become the extra room you have been pretending it could be.",
    category: "Room Addition",
    date: "December 5, 2024",
    readTime: "10 min read",
    image: "/images/hero-renos101.jpg",
    content: [
      "Attic conversions look free because the roof is already there. The roof is not a room. Height, floor structure, stairs, insulation, and fire escape still have to be invented. This lesson is how you decide whether the loft is a bedroom or a very sincere storage idea.",
      "Measure the height that counts, not the peak you stood under once. Codes typically want a decent portion of the floor to clear a minimum ceiling height — often around 2.1 m in Australian habitable rooms, but your certifier is the source, not a blog. The room shrinks as you walk toward the eaves. The bed you imagined may only fit in the middle like a raft.",
      "Storage attics are often not framed for living loads. Joists that hold insulation and Christmas do not automatically hold people and a wardrobe. An engineer looks cheap next to a bounce you discover after the floor is down.",
      "Stairs are the silent room-eater. A real stair needs going, rise, headroom at the bottom, and a hole in the ceiling below. A ladder is not a daily entrance. If the only way up eats the hallway, you have not gained a room. You have relocated the problem.",
      "Insulation and ventilation swap jobs when you inhabit the roof. The thermal line moves to the rafters. Ventilation still has to work or you will grow a climate. Confusing the two is how mould starts a residency.",
      "Light, egress, and fire separation are not styling. If it is a bedroom, you need a way out that is not a vibe. Dormers and roof windows have lead times and flashing details that leak if rushed. Order early.",
      "Services: power, smoke alarms, heating, and possibly a bathroom if you have become ambitious. A bathroom in a roof is a plumbing and waterproofing project hanging over someone else's ceiling. Price it like that.",
      "Council and certifier first. Some lofts are straightforward. Some roofs are a no. This is planning, not an approval. Draw the section before you buy the rug.",
      "Peel Boss rule: if the only honest headroom is where you were standing for the photo, it is not a room yet. It is an attic with a marketing department.",
    ],
  },
  {
    slug: "basement-finishing",
    title: "Basement Finishing: The Room That Costs More Than You Think and Delivers Less Than You Imagined",
    excerpt: "A realistic guide to finishing a basement that helps you budget for the reality instead of the dream.",
    category: "Room Addition",
    date: "November 28, 2024",
    readTime: "10 min read",
    image: "/images/hero-renos101.jpg",
    content: [
      "Basements are damp or they are waiting. Water vapour moves through concrete. Groundwater presses on walls. This is physics, not a bad attitude. Finish a wet basement and you have built a very tidy home for mould. This lesson is the order: moisture, then height, then the pretty stuff.",
      "Moisture management is job one. Drainage, grading away from the house, a sump if you need one, and a strategy for the walls — not a feature paint. If you can smell the room after rain, you do not have a finishing project. You have a water project that is pretending.",
      "If you want to call it a bedroom, egress rules arrive. A window you can climb out of, a path that does not go through a locked garage, and headroom that meets the code. Lot geometry sometimes says no. Better to hear that before the frames go in.",
      "Ceiling height is the daily reality. Ducts, beams, and pipes hang where you wanted a clean plane. Options: soffits, a dropped ceiling, or moving services. Each has a price. A 1.9 m 'rumpus' is a room people duck through and then stop using.",
      "Insulation and a thermal break stop the basement feeling like a car park. Floors need a plan for cold and moisture — not a carpet on a sweating slab. Walls need a system that can dry, not a sealed pretty skin over a wet mass.",
      "Services: extra power, lighting that is not a single tube, heating, and ventilation so the room actually exchanges air. A basement bathroom is a luxury that comes with a pump, a membrane, and a plumber who has done this before.",
      "Hire someone who finishes basements in your neighbourhood, not someone who mostly does kitchens and is 'happy to have a look.' Local water tables have local opinions.",
      "Budget a contingency that assumes the first wall you open has a story. Australian houses with true basements are less common than crawl spaces and sloping sites — if what you have is a cellar or a subfloor, the same moisture rules apply and the same 'it will be fine' speech does not.",
      "Peel Boss rule: a dry, slightly plain basement is a success. A styled basement that smells like a forest floor after rain is a sequel you did not want to green-light.",
    ],
  }
]

export function getBlogPost(slug: string) {
  return blogPosts.find((post) => post.slug === slug)
}
